### ISSUE TITLE
which pyxel versions are supported?

### ISSUE THREAD

**Issue by seahurt** [kawa-mineka/CODE-OF-PYTHON#2]
I got error when I run the code.

```
pygame 2.1.2 (SDL 2.0.16, Python 3.8.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "code-of-python.py", line 13379, in <module>
    App()
  File "code-of-python.py", line 2647, in __init__
    pyxel.init(WINDOW_W,WINDOW_H,caption="CODE OF PYTHON",fps = 60,quit_key=pyxel.KEY_NONE) #ゲームウィンドウのタイトルバーの表示とfpsの設定(60fpsにした),キーボード入力による強制終了は無しとする
TypeError: init() got an unexpected keyword argument 'caption'
```

after remove `caption='CODE OF PYTHON'`, another error appeared

```
pygame 2.1.2 (SDL 2.0.16, Python 3.8.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "code-of-python.py", line 13379, in <module>
    App()
  File "code-of-python.py", line 2649, in __init__
    self.load_system_data()              #システムデータをロードする関数の呼び出し
  File "code-of-python.py", line 3430, in load_system_data
    self.game_difficulty = pyxel.tilemap(0).get(0,120) - 16 #数字の[0]はアスキーコード16番なので16引いて数値としての0にしてやります
AttributeError: 'builtins.Tilemap' object has no attribute 'get'
```

seems some api of pyxel has changed

my version of pyxel and pygame are as followed:
```
pyxel==1.6.5
pygame==2.1.2
```
I am using Ubuntu 20.04, conda 4.11.0, python 3.8.12 in the conda env

**Comment by seahurt** [comment]
OK, I got it. The program is not supported in linux platform. You developed it in Windows System.
